project_id = "zoe-system"

[db]
major_version = 17

[auth]
enable_signup = false
enable_anonymous_sign_ins = false
minimum_password_length = 8

[auth.email]
enable_signup = false
enable_confirmations = true
double_confirm_changes = true
secure_password_change = true

[auth.sms]
enable_signup = false

[functions.register]
verify_jwt = false

[functions.reset-password]
verify_jwt = false
