// ព្រំដែន module ៖ [បន្ទាត់ចាប់ផ្តើម, ផ្លូវ module]
// រាល់ declaration កម្រិតកំពូលធ្លាក់ចូល module ដែលព្រំដែនរបស់វាគ្រប។
module.exports.MODULE_BOUNDS = [
  [1,     'core/runtime'],
  [126,   'core/actions'],
  [266,   'core/elapsed'],
  [271,   'ui/boot-splash'],
  [343,   'core/clock'],
  [436,   'core/text'],
  [511,   'ui/modal'],
  [584,   'services/network'],
  [861,   'services/firebase-sdk'],
  [969,   'services/connection'],
  [1176,  'services/firebase-init'],
  [1264,  'services/crypto'],
  [1437,  'features/pin'],
  [1606,  'features/biometric'],
  [1890,  'features/app-lock'],
  [2226,  'features/config'],
  [2528,  'features/config-qr'],
  [2646,  'features/lookup-config'],
  [2810,  'features/sheet-import'],
  [3448,  'features/customer-table-prefetch'],
  [3577,  'features/health-check'],
  [3811,  'features/lookup-api'],
  [3938,  'features/customer-table'],
  [4194,  'features/auto-lookup'],
  [4591,  'features/exchange-rate'],
  [4665,  'features/session'],
  [4857,  'features/license'],
  [4984,  'features/auth'],
  [5134,  'services/db-listeners'],
  [5422,  'domain/cleanup'],
  [5994,  'domain/barcode'],
  [6124,  'ui/toast'],
  [6258,  'core/timezone'],
  [6356,  'boot/boot-load'],
  [6447,  'ui/modal-stack'],
  [6529,  'domain/ledger'],
  [6816,  'domain/pickup'],
  [7037,  'domain/collected'],
  [7332,  'features/stats-modals'],
  [7455,  'ui/page-nav'],
  [7577,  'ui/panel-motion'],
  [7871,  'ui/chrome-autohide'],
  [7986,  'ui/perf'],
  [8061,  'ui/pull-to-refresh'],
  [8455,  'ui/more-menu'],
  [8608,  'features/export'],
  [8940,  'features/monthly-report'],
  [9253,  'features/daily-stats'],
  [9436,  'services/camera'],
  [9633,  'services/scan-engine'],
  [9863,  'ui/history-refresh'],
  [9894,  'features/phone-suggest'],
  [10137, 'domain/registry'],
  [10287, 'features/locker'],
  [10479, 'features/scan-remove'],
  [10637, 'features/locker-assign'],
  [10826, 'ui/entry-list'],
  [10991, 'features/scan-action'],
  [11296, 'features/barcode-ops'],
  [11941, 'features/entry-ops'],
  [12374, 'features/trash'],
  [12620, 'features/restore'],
  [13004, 'services/history-write'],
  [13278, 'ui/history-row'],
  [13418, 'features/zto-status'],
  [13985, 'features/zto-list-sync'],
  [14524, 'ui/history-render'],
  [14593, 'features/clear-history']
];

// ក្រុមរបស់ state ដែលប្រែប្រួល (`let` កម្រិតកំពូល ១៧៦)
module.exports.STATE_GROUPS = {
  firebaseState: ['authButtonIsLoggedIn','firebaseConfig','fb','auth','db','dbRefHistory','dbRefDeleted','dbRefDailyRevenue','dbRefMonthlyRevenue','dbRefDailyPickup','dbRefDailyCollected','dbRefExchangeRate','dbRefConnected','dbRefServerTimeOffset','authUnsubscribe','authRecoveryTimeout','authGeneration','sessionExpiryCheck','isDatabaseConnected','hasEverConnectedToDatabase','networkJustReturned','isInitializingFirebase','isDatabaseInitialized','dbListenersFailed','dbListenerRecoveryTimer','dbListenerRecoveryAttempt','lastDbListenerAttemptAt','dbListenerOutageNoticeShown','dbListenerPendingSeen','dbListenerProgressAt','dbListenerGeneration','infoListenersFailed','infoListenerRecoveryTimer','infoListenerRecoveryAttempt','infoListenerGeneration','reconnectWatchdogTimer','reconnectWatchdogAttempt','lastForcedReconnectAt','firebaseSdkRetryTimer','firebaseSdkRetryAttempt','lastFirebaseSdkAttemptAt','lastFirebaseSdkReloadAt','lateFirebaseSdkListenerArmed','firebaseSdkUnavailable','sdkUnavailableNoticeShown','serverTimeOffsetMs','serverClockTrusted','autoLoginAttempted','sessionExpiryCheckInFlight','licenseRecheckInFlight'],
  dataState: ['scanHistory','deletedItems','dailyRevenueData','monthlyRevenueData','dailyPickupData','dailyCollectedData','exchangeRateRiel','pickupResetInFlight','pickupLedgerRepairDone','pickupLedgerRepairRunning','exchangeRateSaveInFlight','historyPatchFlushInFlight','registryReleaseFlushInFlight','deletedCleanupInFlight','cleanupResumeInFlight','clearHistoryInFlight','recentPhonesSignature'],
  scanState: ['codeReader','liveScanCodeReader','scanConfirmCode','scanConfirmCount','scanConfirmAt','scanVideoResumeTimer','currentStream','isCameraScanning','isCameraStarting','cameraRequestId','pendingLoadedMetadataHandler','nativeLoopActive','zxingLoopActive','liveScanWidthIndex','liveScanCostEma','lastDecodedVideoTime','staleFrameStreak','freshFrameGateUsable','currentVideoTrack','torchOn','nativeDetector','ownCaptureCanvas','ownCaptureCtx','pendingBarcode','lastScannedCode','lastScanTime'],
  uiState: ['isModalOpen','phoneModalDismissPromptOpen','searchTimer','currentFilterMode','customFilterDate','editingItemId','markingItemId','activeEditingBarcode','activeParentItemId','pendingRestoreId','currentAppPage','panelGlideTokens','panelGlideEpoch','panelGlideRelease','chromeHidden','pdfExportOriginalTitle','monthlyReportMonth','lastRecallSignature','pendingHistoryViewRefresh','phoneSuggestItems','phoneSuggestActiveIndex','phoneSuggestHideTimer','deletedSearchQuery','activeLocker','entryScanMode','lockerBarcodeIndex','pendingLockerCode','lockerAssignGeneration','pendingScannedRemoval','scanRemoveInFlight','pendingPermanentDeleteId','lastEnteredLocker','globalAudioCtx','perfSamplePending','displayHz','displayHzMeasured'],
  securityState: ['lookupSecretKey','pinTargetAction','isVerifyingPin','biometricUnlockInFlight','appIsLocked','appLockBusy','appLockExcuseAt','appLockVeiled','configQrReader','configQrStream','configQrScanActive'],
  lookupState: ['customerDataTableRows','customerDataTableFetchedAt','customerDataTableFetchPromise','customerDataTableSessionGeneration','customerDataTableLastFailedAt','ztoWarmSoonTimer','ztoWarmSoonArmedAt','customerTableRetryTimer','customerTableFailStreak','customerTableSoonTimer','customerTableSoonArmedAt','customerTableIsPartial','sheetScriptVersionSeen','ztoWarmupAt','ztoWarmupInFlight','lookupLockedNoticeShown','pendingLookupUnlockBarcode','pendingLookupUnlockResolve'],
  sheetImportState: ['sheetImportKey','sheetImportUrl','sheetImportPassword','sheetImportWorkbook','sheetImportSheetRows','sheetImportHeaders','sheetImportSignature','sheetImportBusy'],
  ztoState: ['ztoStatusLoaded','ztoStatusSweepTimer','ztoStatusInFlight','ztoStatusLastSweepAt','ztoStatusFailStreak','ztoStatusBannerSig','ztoStatusModalSig','ztoStatusSweepCursor','ztoListSyncInFlight','ztoListSyncResult']
};

// ការផ្លាស់ទីតាម *ឈ្មោះ* ៖ declaration ខ្លះជា leaf ពិត ➜ ដាក់វានៅ core/
// ដើម្បីកុំឲ្យ core/state.ts ពឹងលើ module កម្រិតលើ (វដ្ត import)។
module.exports.DECL_OVERRIDES = {
  appLocalStore: 'core/storage',
  appSessionStore: 'core/storage',
  safeStoreGet: 'core/storage',
  safeStoreSet: 'core/storage',
  safeStoreRemove: 'core/storage',
  DRAWER_GROUP_KEY: 'core/storage-keys',
  FIREBASE_SDK_RELOAD_KEY: 'core/storage-keys',
  LOOKUP_KEY_DB_NAME: 'core/storage-keys',
  BIOMETRIC_STORAGE_KEY: 'core/storage-keys',
  APP_LOCK_SESSION_KEY: 'core/storage-keys',
  APP_LOCK_PREF_KEY: 'core/storage-keys',
  SHEET_IMPORT_STORE_KEY: 'core/storage-keys',
  SHEET_IMPORT_SECRET_SALT: 'core/storage-keys',
  AUTH_STUCK_RECOVERY_FLAG: 'core/storage-keys',
  CLEANUP_JOURNAL_KEY: 'core/storage-keys',
  LOCKER_PREFIX_KEY: 'core/storage-keys',
  LOCKER_COUNT_KEY: 'core/storage-keys',
  ACTIVE_LOCKER_KEY: 'core/storage-keys',
  ENTRY_SCAN_MODE_KEY: 'core/storage-keys',
  ZTO_STATUS_STORE_KEY: 'core/storage-keys',
  ZTO_AUTOCLOSE_KEY: 'core/storage-keys',
  ZTO_LISTSYNC_KEY: 'core/storage-keys',
  APP_VERSION: 'core/version'
};
